include:
  - notes-backend/compose.yaml
  - notebooks-backend/compose.yaml

services:
  reverse-proxy:
    image: nginx:1.27.0
    ports:
      - "5000:80"
    depends_on:
      - notebooks
      - notes
    volumes:
      - type: bind
        source: ./reverse-proxy/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - notes-app-net

networks:
  notes-app-net:
    
    